gateways:
  ducklake:
    connection:
      type: duckdb
      catalogs:
        ducklake:
          type: ducklake
          path: postgres:dbname={{ env_var('POSTGRES_DB') }} user={{ env_var('POSTGRES_USER') }} password={{ env_var('POSTGRES_PASSWORD') }} host={{ env_var('POSTGRES_HOST') }} port={{ env_var('POSTGRES_PORT', '5432') }} sslmode=require
          data_path: "{{ env_var('DUCKLAKE_DATA_PATH') }}"
          metadata_schema: "{{ env_var('DUCKLAKE_NAME') }}"
      extensions:
        - ducklake
        - httpfs
      secrets:
        - type: s3
          key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
          secret: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
          region: "{{ env_var('AWS_REGION', 'auto') }}"
          endpoint: "{{ env_var('R2_S3_ENDPOINT').replace('https://', '')}}"

    state_connection:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      database: "{{ env_var('POSTGRES_DB') }}"
      sslmode: "require"

default_gateway: ducklake

model_defaults:
  dialect: duckdb
  start: 2024-8-1
  cron: '@weekly'

linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion
    - noambiguousprojections

cicd_bot:
  type: github
  auto_categorize_changes:
    external: full
    python: full
    sql: full
    seed: full
  default_pr_start: "1 week ago"
  skip_pr_backfill: false
  run_on_deploy_to_prod: false
  invalidate_environment_after_deploy: false
